myBlog/urls.py
from django.urls import path

from myBlog import views

urlpatterns = [
    # FunctionBasedView
    # path('', views.index),
    # path('<int:pk>/', views.single_post_page),

    # ClssBasedView
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('<int:pk>/new_comment', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('tag/<str:slug>/', views.tag_page),
    path('search/<str:q>/', views.PostSearch.as_view()),
]

myDjangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # IP 주소/admin/
    path('blog/', include('myBlog.urls')),  # IP 주소/blog/
    path('', include('single_pages.urls')),  # IP 주소/
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myBlog/models.py
import os

from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        #  주어진 클래스 안의 지정된 명령어 안에서 설정값 지정
        verbose_name_plural = 'Categories'  # verbose_name_plural -> 있는 옵션임


class Post(models.Model):  # 클래스 이름이 곧 모델 이름
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)  # 미리 보기
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)

    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    # Post의 외래키로 지정된 User 객체가 삭제되어도 해당 User가 게시한 Post 객체는 없어지지 않도록 함
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    # null=True -> 아무 값도 지정되지 않아도(null 값이어도) 됨 / blank=True -> null값 조차 입력되어 있지 않은 객체의 경우 비어있어도 됨
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}] {self.title} - {self.author}     {self.created_at}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)  # os.path.basename()으로 경로 빼고 이름만 추출해줌

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    # get_absolute_url 함수 통해 해당 모델의 객체가 사이트의 어느 부분에 있는지 확인 가능
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

myBlog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

myBlog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from myBlog.models import Post, Category, Tag, Comment
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404


# def index(request):
#     posts = Post.objects.all().order_by('-pk')
#     return render(request, 'blog/index.html', {'posts': posts})
#
#
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)
#     return render(request, 'blog/single_post_page.html', {'post': post})


# class view 이용하는 경우 템플릿 이름 자동 설정됨 ; 모델명_list.html, 모델명_detail.html
# templates 하위 디렉토리 이름을 앱 이름과 동일하게 해줘야 파일 찾기 가능
class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    # 매개변수 => post_list

    # get_context_data() => 페이지에 원하는 내용 띄우기 위해 생성한 함수
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context


class PostDetail(DetailView):
    model = Post

    # 매개변수 => post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()  # 템플릿으로 전달할 내용을 담음
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['comment_form'] = CommentForm  # 컨텍스트에 CommentForm 객체 함께 보내 화면에서 해당 폼 사용
        return context


class PostCreate(CreateView, LoginRequiredMixin, UserPassesTestMixin):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']

    # CreateView 호출 뷰 ->  모델명_form.html
    # 뷰에 form 이름으로 전달됨

    # ModelFormMixin 클래스 상속 함수 -> 입력받은 내용이 모델에 적합한지 확인

    def test_func(self):
        return self.reqeust.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and current_user.is_superuser or current_user.is_staff:  # 요청 보낸 유저가 인가된 유저라면
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')

            for t in tag_list:
                t = t.strip()
                tag, created = Tag.objects.get_or_create(name=t)
                if created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)  # 생성된 객체에 생성한 tag 추가
            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, **kwargs):
        context = super(PostCreate, self).get_context_data()  # 템플릿으로 전달할 내용을 담음
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context


class PostUpdate(UpdateView, LoginRequiredMixin):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    template_name = 'myBlog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):  #dispatch 가 request 시 어떤 http 메소드를 사용해 들어오는 지 파악하고 POST면 form_valid 실행
        response = super(PostUpdate, self).form_valid(form)

        self.object.tags.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tag_list = tags_str.split(';')

        for t in tag_list:
            t = t.strip()
            tag, created = Tag.objects.get_or_create(name=t)
            if created:
                tag.slug = slugify(t, allow_unicode=True)
                tag.save()
            self.object.tags.add(tag)  # 생성된 객체에 생성한 tag 추가

        return response

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()  # 템플릿으로 전달할 내용을 담음

        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tag_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user  # 댓글 작성 요청자는 로그인한 유저
                comment.save()
                return redirect(comment.get_absolute_url())

        else:  # 요청 메소드가 POST가 아닌 경우
            return redirect(post.get_absolute_url())
    else:  # 요청자가 로근이 유저 아닌 경우
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    # 템플릿 매개변수 -> comment_form.html

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(request, 'myBlog/post_list.html', {
        'category': category,
        'post_list': post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    return render(request, 'myBlog/post_list.html', {
        'tag': tag,
        'post_list': post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })


class PostSearch(PostList):  # PostList 에서 지정한 ListView 상속받음, post_list 변수로 접근 가능, post_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=1)).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q}({self.get_queryset().count()})'
        return context

myBlog/templates/myBlog/base.html
<!DOCTYPE html>
<!--static 디렉터리 로드-->
{% load static %}
<html lang="KO">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}BLOG{% endblock %}</title>
    <!--하나의 css 파일로 정적 스타일 적용하기-->
    <link href="{% static 'myBlog/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
          media="screen"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/05bb31ed0b.js" crossorigin="anonymous"></script>
</head>

<body>
{% include 'myBlog/navbar.html' %}

<!--블로그 게시물 부분-->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-lg-9" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
        <div class="col-md-4 col-lg-3">
            {% include 'myBlog/sidebar.html' %}
        </div>
    </div>
</div>

{% include 'myBlog/footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>
</html>

myBlog/templates/myBlog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 20181003 엄지우</p>
    </div>
</footer>

myBlog/templates/myBlog/navbar.html
{% load socialaccount %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">INTERNET PROGRAMMING</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/blog/">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about_me/">About_Me</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <!-- Modal -->
      <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="loginModalLabel">
                <i class="fa-solid fa-right-to-bracket"></i> LogIn
              </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-6">
                  <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                    href="{% provider_login_url 'google' %}">
                    <i class="fa-brands fa-google"></i> LogIn with Google
                  </a>
                  <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                    href="/accounts/login/">
                    <i class="fa-brands fa-google"></i> LogIn with Email
                  </a>
                </div>
                <div class="col-6">
                  <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                    href="/accounts/signup/">
                    <i class="fa-regular fa-envelope"></i> SignUp with Email
                  </a>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

myBlog/templates/myBlog/post_detail.html
{% extends 'myBlog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{post.title}} - Blog
{% endblock %}
{% block main_area%}
<!-- Post content-->
<div id="post-area">
    <!-- Post header-->
    <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">{{post.title | lower}}</h1>
        {% if post.hook_text %}
        <h5 class="text-muted"> {{post.hook_text}} </h5>
        {% endif %}
        <!-- Post meta content-->
        <div class="text-muted fst-italic mb-2">{{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author | upper}}
        </div>
        <!-- Post categories-->
        {% if post.category %}
            <a class="badge bg-secondary text-decoration-none link-light" href="{{post.category.get_absolute_url}}">{{post.category}}</a>
        {% else %}
            <a class="badge bg-secondary text-decoration-none link-light" href="/blog/category/no_category/">미분류</a>
        {% endif %}
    </header>

    {% if user.is_authenticated and user == post.author %}
        <a class="btn btn-info float-right" href="/blog/update_post/{{post.pk}}/" role="button">
                <i class="fas fa-pen">Edit Post</i>
        </a>
    {% endif %}
    <!-- Preview image figure-->
    {% if post.head_image %}
    <figure class="mb-4"><img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{post.title}}의 head_image"/>
    </figure>
    {% else %}
    <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/400" alt="외부 사이트에서 받아온 랜덤 이미지"/>
    {% endif %}
    <!-- Post content-->
    <section class="mb-5">
        <p class="fs-5 mb-4">{{post.content}}</p>

        {% if post.tags.exists %}
        {% for tag in post.tags.iterator %}
        <span class="badge badge-pill badge-light">
            <i class="fas fa-tag"><a href="{{tag.get_absolute_url}}">{{tag}}</a></i>
        </span>
        {% endfor %}
        {% endif %}

        {% if post.file_upload %}
        <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
            {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
            <i class="fa-regular fa-file-excel"></i>
            {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
            <i class="fa-regular fa-file-word"></i>
            {% else %}
            <i class="fa-regular fa-file"></i>
            Download {{post.get_file_name}}
            {% endif %}
        </a>
        {% endif %}
    </section>
</div>
<!-- Comments section-->
<div class="mb-5" id="comments-area">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            {% if user.is_authenticated %}
            <form class="mb-4" id="comment-form" method="post" action="{{post.get_absolute_url}}new_comment/">
                {% csrf_token %}
                <div clalss="form-group">
                    {{comment_form | crispy}}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            <a role="button" class="btn btn-dark btn-block btn-small"
               href="#" data-toggle="modal" data-target="#loginModal">
                Login and Leave a Comment
            </a>
            {% endif %}
            {% if post.comment_set.exists %}
            {% for comment in post.comment_set.iterator %}
            <!-- Single comment-->
            <div class="media d-flex" id="comment-{{comment.pk}}">
                <div class="flex-shrink-0">
                    <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."/>
                </div>
                <div class="media-body ms-3">
                    {% if user.is_authenticated and comment.author == user  %}
                        <a role="button" class="btn btn-sm btn-info float-right"
                           href="/blog/update_comment/{{comment.pk}}/">
                            Edit
                        </a>
                    {% endif %}
                    <div class="fw-bold">
                        {{comment.author.username}}
                        <small class="text-muted">{{comment.created_at}}</small>
                    </div>
                    <p>{{comment.content | linebreaks}}</p>
                    {% if comment.created_at != comment.modified_at %}
                        <p class="text-muted float-right">
                            <small>Updated : {{comment.modified_at}}</small>
                        </p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

myBlog/templates/myBlog/post_form.html
{% extends 'myBlog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Create a New Post</h1>
    <hr/>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form | crispy}}

            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
            </div>
        </table>

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

myBlog/templates/myBlog/post_list.html
{% extends 'myBlog/base.html' %}

{% block main_area%}
    {% if user.is_authenticated %}
        {% if user.is_authenticated or user.is_superuser or user.is_staff %}
            <a class="btn btn-info float-right" href="create_post/" role="button">
                <i class="fas fa-pen">New Post</i>
            </a>
        {% endif %}
    {% endif %}

    <h2>Blog
        {% if search_info %}
            <span class="badge badge-secondary">{{search_info}}</span>
        {% endif %}

        {% if category %}
        - <span class="badge badge-pill">{{category}}</span>
        {% endif %}
        {% if tag %}
        - <span class="badge badge-pill"><i class="fas fa-tag">{{tag}}</i></span>
        {% endif %}
    </h2>
<!--        &lt;!&ndash;블로그 게시물 부분&ndash;&gt;-->
<!--        <div class="container">-->
<!--          <div class="row">-->
<!--            <div class="col-md-8 col-lg-9" id="main-area">-->
{% if post_list.exists %}
{% for p in post_list %}
<!-- 게시물 하나 -->
<div class="card mb-4" id="post-{{p.pk}}">
    {% if p.head_image %}
    <img class="card-img-top" src="{{p.head_image.url}}" alt="{{p}}의 head_image"/>
    {% else %}
    <img class="card-img-top" src="https://picsum.photos/seed/{{p.pk}}/800/400" alt="외부 사이트에서 받아온 랜덤 이미지"/>
    {% endif %}
    <div class="card-body">
        {% if p.category %}
        <span class="badge badge-secondary float-right"><a href="{{p.category.get_absolute_url}}">{{p.category}}</a></span>
        {% else %}
        <span class="badge badge-secondary float-right"><a href="/blog/category/no_category/">미분류</a></span>
        {% endif %}
        <h2 class="card-title">{{p.title | upper}}</h2>
        {% if p.hook_text %}
        <h5 class="text-muted"> {{p.hook_text}} </h5>
        {% endif %}
        <p class="card-text">{{p.content | truncatechars:100 }}</p>

        {% if p.tags.exists %}
        {% for tag in p.tags.iterator %}
        <span class="badge badge-pill badge-light">
            <i class="fas fa-tag"><a href="{{tag.get_absolute_url}}">{{tag}}</a></i>
        </span>
        {% endfor %}
        {% endif %}
        <br>

        <a class="btn btn-primary" href="{{p.get_absolute_url}}">Read more →</a>
    </div>
    <div class="card-footer">
        <div class="small text-muted">{{p.created_at | date:"Y-m-d h:m:s"}}</div>
        <a href="#">{{p.author|upper}}</a>
    </div>
</div>

{% endfor %}
{% else %}
<h5>아직 게시물이 없습니다.</h5>
{% endif %}

<!-- Pagination-->
{% if is_paginated %}
<nav aria-label="Pagination">
    <hr class="my-0"/>
    <ul class="pagination justify-content-center my-4">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}" tabindex="-1" aria-disabled="true">Older</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#!">Older</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

myBlog/templates/myBlog/post_update_form.html
{% extends 'myBlog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Update Post</h1>
    <hr/>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form | crispy}}

            <div>
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
            </div>
        </table>

        <button type="submit" class="btn btn-primary float-right">Submit</button>


    </form>
{% endblock %}

myBlog/templates/myBlog/sidebar.html
<!-- Search widget-->
<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-magnifying-glass"></i> Search
    </div>
    <div class="card-body">
        <div class="input-group">
            <input id="search_input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..."
                   aria-describedby="button-search"/>
            <!-- onclick 옵션 통해 호출하고자 하는 자바스크립트 함수 지정 -->
            <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
        </div>
    </div>
</div>

<!-- 자바 스크립트 함수 정의 -->
<script>
    function searchPost(){
        let search_value = document.getElementById('search_input').value.trim();
        if(search_value.length > 1){
            location.href = "/blog/search/"+search_value+"/";
        }
        else{
            alert('검색어('+search_value+')가 너무 짧습니다.')
        }
    };

    // addEventListener('이벤트', 이벤트 발생 시 호출할 함수)
    document.getElementById('search_input').addEventListener('keyup', function(event){
        if(event.key === 'Enter'){
            searchPost();
        }
    });
</script>

<!-- Categories widget-->
<div class="card mb-4" id="category_card">
    <div class="card-header">Categories</div>
    <div class="card-body">
        <div class="row">
                <ul class="list-unstyled mb-0">
                    {% for c in categories%}
                    <!--여기 categories 는 views.py 에서 get_context_data()로 받은 categories -->
                    <li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
                    {% endfor %}
                    <li><a href="/blog/category/no_category/">미분류 ({{no_category_post_count}})</a></li>
                </ul>
        </div>
    </div>
</div>